---

# Use Ansible to configure your 'primary Ethernet interface' as follows:
#
# interface description:    *** IN USE ***
# switchport mode:          access
# VLAN:                     700

- name: Arista-Ansible Exercise2
  hosts: arista

  tasks:
    - name: Setting Ethernet5 description
      eos_interface: name=Ethernet5 description="*** IN USE ***"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Setting Ethernet5 to access mode, vlan 700
      eos_switchport: name=Ethernet5 mode=access access_vlan=700
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
