---

# 4. Use Ansible to restore your 'primary Ethernet interface' back to the following state (or your secondary interface depending on which one you used):
# description:                    <none>
# switchport mode:           access
# access VLAN:                1
# trunk allowed VLANs:    all

# Also use Ansible to remove the three VLANs that you configured.

- name: Arista-Ansible Exercise4
  hosts: arista

  tasks:
    - name: Setting Ethernet5 description to none
      eos_interface: name=Ethernet5 description=""
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Setting Ethernet5 to access mode, vlan 1, all trunk vlans allowed
      eos_switchport: name=Ethernet5 mode=access access_vlan=1 trunk_allowed_vlans=1-4094
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Delete VLANs
      eos_vlan: name={{ item.vlan_name }} vlanid={{ item.vlan_id }} state=absent
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
        - {vlan_name: WHITE, vlan_id: 700}
        - {vlan_name: BLACK, vlan_id: 701}
        - {vlan_name: BROWN, vlan_id: 702}
